server:
  port: 8768
#  context-path: /member
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: pay
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  #数据库连接信息
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/xbao_pay
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
############################################################
################-----支付宝接口调用配置----#################
############################################################
alipay:
  appId: 2016101100657414
  merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCQJgQZFSuwa0GGiP+stP4DU+ksEmUonRRunWEObi+P1+xFyjVAjY9s/AUMul2anmkoPrbgOXOJIWgHC44s/AERPGBXCldDiSUz86ix9jg+z09ogV6H+IA6zYOLLdZqOq0+LBmFjP1tdiH/7KpQLEoXH+hqMlAZ7puK9x7bofDyy4IqrPkHBEKXmib46ITydoD5LNEAYayM2HfSoh2WsaxOE4f7U+Pj4rRdv8vqRWGGznLlQ2nFDH8oMqbG21sVl8wDYPf7NjRLBMMVHuAPY5k1crFuWcvascPGcn2feN3wDtFaWkFAUqSqIVl/SMrrIxvUl/5qIvvAlI1pXFWMqiwbAgMBAAECggEAA0Zp12wMtxBox7a7IGBoWQkCBjdQxxByk2TN/LbyK7F7M8a5WQMeXBqJvtVJJScuOnTaUNPdVSNGKsrPayQ6nfqiMbgRbX5jMv/5ODng40RwiG5QCITT3QIoV/Qtp/I3V29HESq341HIyfjFkda/xDC8ZhVIjp5GOG0O7WyLfeirC13OgHo4vsQ+Dbj+ozgtn94qaW9BjuTSzZy9YPfhWvQaB9SkXMl7eT/Ujbs5ScDZo5kVALD/8p44mvELMv1FSaHmCJB8j6A81S782vv6y+Axu+yPdrbGAs55eH4VFbx9l+KhBVaOBhwVxP0zGJo1FAGl3yDx97hpRp/N45X1CQKBgQDHD8VvGEqUmOa4lPhuQqx5hPyNWk1LFzMHoNR07/7J3yg6jMk0KTgqV7123zoM+AtlXHXC6/W/j7x149o27S/G0Dd+t7Ewjn07AjaIGgkQ0VcuC10gSTsZY2rsHwxG8NLuSt8lJpxWlEfZj6pbwx6/PFkWG688stzPcRGxTdB65wKBgQC5YT+WmzdSBAhk8Lz21+FEIucloVKeo9RBLvWMKVGwmlaWgzq0/DJ9LM/9x4PZHiAri24g9JjJog+DCkOnKS9olzEYj5gTtNPJ2YPCYuZY9sNhqyVZrv6JGuiS4fvgyPpTb7jZDewOW6Io7Y+iQLjwwmpBDzbeDtso5xXFiEoyrQKBgA1sF9D031qDsNLzYIj2v/B1sh3J3/pXNx6ljo3P/OsZu/musoZs3Rel0OWqCZ0EQKh2Ao7BIFHpXDjKw1T+y0Dpm0RVGIKAqRsIfCrTLpdOtkUpiP77URvWI0iGk2pZJK/ipoc3wkToPKwDzuXfEzyr0gn2letO2Cq4ogvFhnAzAoGAVen5E26KG+ucjFN58Biq4O4gHDOA297njvIZgMThhCxzNrxI5/n92D99gYsG0wgANs4e0w0pBkGiWMPYCM+wlhOEAHMEMxXaFbFGPD+jq9VpRYmQ/Nh6RMaAxRoQpuPeB+8+RvIJ1bmoFLnMmJDQZVxk7BQGBLHz5if60hpQ8N0CgYEAgBnWUr+kiAPRcfD0RXQKf87cd1pFYtOz3ZeVz8jVAndtwGk5n4LZ+cF/SXnzp51TuHnq+hWeaJiTN9r7KNrhGmkhvqboj3aw8uwipYGmIFwCgHTSH8m81z8M02Cp2iXJ9yjl4x2+l2VZamBW2PXThuGGRie17VwKQLmai9OH8t4=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhEgh51iKHMmSH7ahdlQYwxPUdtG2XsrdR6sSqmTHYWZPxOPC9zr8B5LfxE1JM1DKOR0XiUJBRKOwL6MCMGvE+h/0JvKog5tXyDk2l/FWIiYGKuUTGo8dRijMRt5OKO6IJQWLTuTJcEJV1/19QqLoG5pUzLaF09kKKU9GwWBoyrNdTlt+8uyaq2+TGQ/W74ADkkqp70Ao/ZunTOHmThAEjOL05OGpbC6hrYa3ku8DnyebeJuvAOFXt3lcbKvfUMy8/rhqhIID88O7fKdW6fZlnE4lsZpMuHK3+ZG0py+hfB65XhbcMlgKsvaBfUBXIVW7ZNc7l/JsR4HP6QVkDv+X3QIDAQAB
  returnUrl: http://6c3jyq.natappfree.cc/alibaba/callBack/returnUrl
  notifyUrl: http://6c3jyq.natappfree.cc/alibaba/callBack/notifyUrl
  signType: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  logPath: C:\